import type { Metadata } from "next";
import "@/style/globals.css";
import GlobalsUserInfo from "@/components/globalslayout/GlobalsUserInfo";
import GlobalsNav from "@/components/globalslayout/GlobalsNav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

type Props = Readonly<{ children: React.ReactNode }>;

const RootLayout = ({ children }: Props) => {
  return (
    <html lang="ko">
      <body>
        <div className="mx-auto flex h-[100vh] w-[90%] max-w-[1920px] gap-[20px] py-[100px]">
          <aside className="borderline w-[20%]">
            <GlobalsUserInfo />
          </aside>
          <section className="flex w-[80%]">
            <main className="borderline w-[90%] overflow-hidden">{children}</main>
            <GlobalsNav />
          </section>
        </div>
      </body>
    </html>
  );
};

export default RootLayout;
